server:
  port: 8037
  servlet:
    context-path: /Meli
  tomcat:
    uri-encoding: UTF-8
spring:
  security:
    user:
      name: 5d2662e2-ef84-4922-9cab-d5e46541fdcb
      password: 3a97b852-9f5b-4d3c-b529-c79904783986
      roles: ADMIN
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    url: jdbc:mysql://165.232.153.114:33006/Favorito?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
  devtools:
    livereload:
      enabled: true
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      static_path_pattern: /**



---

constant:
  url:
    MeliUrl: https://api.mercadolibre.com/items?ids=
